version: '3.8'
services:
  postgres:
    build:
      context: docker/services/postgres
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=bookstore
      - POSTGRES_PASSWORD=132456pP#
    volumes:
      - "db-data:/var/lib/postgresql/data"
  
  
  app:
    build:
      context: ./docker/services/app
      dockerfile: Dockerfile
    volumes:
      - ./target:/usr/local/app/tmp
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=132456pP#
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/bookstore
    ports:
      - 8080:8080
    depends_on:
      - postgres
        
volumes:
   db-data: