spring:
  profiles:
    active: local
  application:
    name: bookstore-app
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: false
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  jackson:
    default-property-inclusion: non_null
